apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgB2MDUY67z2YVuWilPNSQSKe7rGotqYAoOW3Y591OL3QhLDelueB7QK+gIR3rUPddsOMXfREmQ446/vZtydnotQ3C09c92zWj9UxGMbbAdc11KImnI8tbk0vNq5gogML1ccVCII/aNQNdOxpf+s7ugyZvmzfMYHq1RDpgb90OnHOlIHY9vbVVeiWp39pJqC8As/5fyMvQ9Av5X0M5USBqpMOyceLceCFZsAMECqxdsGjSqmdbR6/7xHGOSK3c0+LwgOYrnZeYzQ/yaYfD5wfuI1aoDSZa1/W0936pqGFmHkZfXDRDp2XvR017W04hTde9w2wPXHyOUkxLXpSPPAOF/FNnMJkdKUGsikSH5WUoZglM3ezqTwG1huyaGGlYj0i6+225tE5OeX/SvUIvzlsPReOssIBLJ1AICLtO9hdYU+7UPU/MwG+2MF/UeJLZr+gh4nOwpTQ7LpfICJOgubJEfPZZ0SVy4nXDbtlKPKTU/Nk2l8sFDTNA+2SdQz1auu6bOFcBkBYE6ziV+pWTXRX3N50VfnU9Lm0G26140ViMyJhvnS8LLytd4nm/woFR/K/Szpiweu4mHjpXDIFTMaZZRVpZ9We/0/akd0DU0LuV5sB4F7MKo5/gSAclIMM0f931Bie04DFlJVxtmZrV54dZ60JIfrlZ/VRklnAOpUCrETRGTT0P6erdSZ98Fy3ONUpDgpT/97nckt4vn69il8uD+26+5NYEWfEthZhlIg5ufuPP4PyaSBCnHCmfhEyH/pCRzcy0jRVelGeqIjH9N23sGgi8BptqyTdcmhRakW/zBbR5pGr1eUhZx9izskwREPEwmBoCA3JMZJ14wpHzVvRKhHJCRGCsIq9eCpHxA+2Ow2hiCaMcCuO25brg75dwWoocG9F/M6EYOXLXzky4WI4oldcgzgoU52XgVw7fR5Xygsis6U4bQRI9Hmnm6YPoWXGyEq9JtrFAffLMKvOwdmmiMQtoAJw2EoMuSRWUA0C8PNdMrwKo5TH2qeLpwsOHP6M96CLqP8D5/14rrI0HFdSx944UFm2+HtPj1hmIcIk9CnwFnBWG2yS+lr8ukF1pUWW9pbEAK4i7RGwY4NFr4q8bL6y7VXi+UpVqbFKd1bwaQRUtRtR38X/IiugxdfvnRQ2hOX1rleZCYR2UkC9Q4l74iMFYvzF9Iuj84Z6hHmuyr2+HAwAW7Bf0SeBmIXUbtWJxbWyo5JOyl0YhWORYU8BZb9I1f0wBrcVViyKoaRwXsDE+KEz6U7BJQlnWLbdrkmQw1yf0dH9evPzrWdyq7mqghyPAnG+9R+0UREilvtwDpF+ZdqWIrA+CT4ETAXf/lSurS4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

